version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zorman_meni
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      - APP_PORT=8080
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: zorman_meni_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=database_meni
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: zorman_meni_nginx
    ports:
      - "7777:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - app

volumes:
  db_data:
